### ISSUE TITLE
ERR! enfield Build failed: ext must be a string

### ISSUE THREAD

**Issue by albertosantini** [fortes/enfield#39]
Any hint about the following error?

```
$ enfield -v
enfield 0.4.0
$ enfield build
info enfield Configuration File: _config.yml
info enfield Source: ./
info enfield Destination: _site
info generate Begin generation
ERR! enfield Build failed: ext must be a string
$
```

**Comment by fortes** [comment]
I'm guessing it's trying to extract a file extension from a file and failing, and that's causing an issue. What are the filenames of the site? If you run with `--log verbose` it may give more info.

**Comment by albertosantini** [comment]
Here the output.

```
$ node ../enfield/bin/enfield.js build --log verbose                                                        
verb enfield Set log level: verbose                                                                         
verb enfield [09:00:10] Received command build                                                              
verb config [09:00:10] Trying to read config from file _config.yml                                          
verb config [09:00:10] Loading config from file _config.yml                                                 
info enfield [09:00:10] Configuration File: _config.yml                                                     
info enfield [09:00:10] Source: ./                                                                          
info enfield [09:00:10] Destination: _site                                                                  
info generate [09:00:10] Begin generation                                                                   
verb generate [09:00:10] Looking for plugins in: C:\My\Dev\snippets\enfield\src\plugins                     
ERR! enfield [09:00:10] Build failed: ext must be a string                                                  
verb enfield [09:00:10] Stack trace: TypeError: ext must be a string                                        
verb enfield   at win32.basename (path.js:325:11)                                                           
verb enfield   at Array.map (native)                                                                        
verb enfield   at C:\My\Dev\snippets\enfield\src\generate.coffee:711:18                                     
verb enfield From previous event:                                                                           
verb enfield   at loadBundledPlugins (C:\My\Dev\snippets\enfield\src\generate.coffee:670:6)                 
verb enfield   at module.exports.exports (C:\My\Dev\snippets\enfield\src\generate.coffee:29:36)             
verb enfield   at Object.module.exports.exports.build (C:\My\Dev\snippets\enfield\src\enfield.coffee:131:5) 
verb enfield   at C:\My\Dev\snippets\enfield\src\enfield.coffee:77:23                                       
$                                                                                                           

```

**Comment by bretonio** [comment]
A similar experience albeit in my case in Arch Linux.

```
verb enfield Set log level: verbose
verb enfield [7:33:04 PM] Received command serve
verb config [7:33:04 PM] Trying to read config from file _config.yml
verb config [7:33:04 PM] Loading config from file _config.yml
info enfield [7:33:04 PM] Configuration File: _config.yml
info enfield [7:33:04 PM] Source: ./
info enfield [7:33:04 PM] Destination: _site
info generate [7:33:04 PM] Begin generation
verb generate [7:33:05 PM] Looking for plugins in: /home/bretonio/.nvm/versions/node/v7.2.0/lib/node_modules/enfield/src/plugins
ERR! enfield [7:33:05 PM] Build failed: "ext" argument must be a string
verb enfield [7:33:05 PM] Stack trace: TypeError: "ext" argument must be a string
verb enfield   at basename (path.js:1354:13)
verb enfield   at Array.map (native)
verb enfield   at /home/bretonio/.nvm/versions/node/v7.2.0/lib/node_modules/enfield/src/generate.coffee:711:18
verb enfield   at _combinedTickCallback (internal/process/next_tick.js:67:7)
verb enfield   at process._tickCallback (internal/process/next_tick.js:98:9)
verb enfield From previous event:
verb enfield   at loadBundledPlugins (/home/bretonio/.nvm/versions/node/v7.2.0/lib/node_modules/enfield/src/generate.coffee:670:6)
verb enfield   at exports (/home/bretonio/.nvm/versions/node/v7.2.0/lib/node_modules/enfield/src/generate.coffee:29:36)
verb enfield   at Object.build (/home/bretonio/.nvm/versions/node/v7.2.0/lib/node_modules/enfield/src/enfield.coffee:131:5)
verb enfield   at Object.serve (/home/bretonio/.nvm/versions/node/v7.2.0/lib/node_modules/enfield/src/enfield.coffee:142:13)
verb enfield   at /home/bretonio/.nvm/versions/node/v7.2.0/lib/node_modules/enfield/src/enfield.coffee:84:23
verb enfield   at _combinedTickCallback (internal/process/next_tick.js:67:7)
verb enfield   at process._tickCallback (internal/process/next_tick.js:98:9)
```

`_config.yml` has only two lines: name (of the project) and `pygments: true`.
