### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by heyallan** [fortes/enfield#41]
I've used jekyll before, but first time trying enfield. I get this error:

![screen shot 2015-07-16 at 14 34 10](https://cloud.githubusercontent.com/assets/1783777/8734575/221a68a8-2bc8-11e5-945f-2c525dc01483.png)

What's wrong here?
Thanks.

**Comment by fortes** [comment]
Hm, not sure. Try running w/ `--log verbose`?

**Comment by heyallan** [comment]
**Thanks. Here's what I get:**

```

15:04:02 @heyallan [myfolder] $ enfield build --log verbose
verb enfield Set log level: verbose
verb enfield [15:05:23] Received command build
verb config [15:05:23] Trying to read config from file _config.yml
verb config [15:05:24] Loading config from file _config.yml
info enfield [15:05:24] Configuration File: _config.yml
info enfield [15:05:24] Source: ./
info enfield [15:05:24] Destination: _site
info generate [15:05:24] Begin generation
verb generate [15:05:24] Looking for plugins in: /usr/local/lib/node_modules/enfield/src/plugins
verb generate [15:05:24] Creating destination directory _site
verb generate [15:05:24] Loading plugin: /usr/local/lib/node_modules/enfield/src/plugins/enfield-extensions.coffee
verb generate [15:05:25] Loading plugin: /usr/local/lib/node_modules/enfield/src/plugins/jekyll-extensions.coffee
verb generate [15:05:25] Loading plugin: /usr/local/lib/node_modules/enfield/src/plugins/markdown.coffee
verb generate [15:05:26] Initialization complete
verb generate [15:05:26] Cleared contents from _site
verb generate [15:05:26] Looking for includes in _includes
verb generate [15:05:26] Looking for layouts in /Volumes/GUEST/.Trashes/501/enfield/_layouts
verb generate [15:05:26] Loading contents from ./
verb generate [15:05:26] Looking for plugins in: 
verb generate [15:05:26] Couldn't load includes from: _includes (ENOENT, stat '_includes')
verb generate [15:05:26] Found includes: []
verb generate [15:05:26] Normalized includes: []
verb generate [15:05:26] Loading posts _posts/2000-01-01-welcome-to-enfield.md
verb generate [15:05:26] Load layouts complete
verb generate [15:05:26] Loaded post: _posts/2000-01-01-welcome-to-enfield.md
verb generate [15:05:26] Content loading complete
verb generate [15:05:26] Plugin, include, layout, and content load complete
verb generate [15:05:26] Reading complete. Running generators
verb generate [15:05:26] Generators complete, preparing to write posts
verb generate [15:05:26] writePages: 1 pages to write

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
  at errnoException (net.js:901:11)
  at Object.afterWrite (net.js:718:19)

15:05:26 @heyallan [myfolder] $ 

```

**Comment by fortes** [comment]
Hm, not quite sure what's going on, but from the log it looks like you're running from within the `.Trashes` folder, which may have restrictions in terms of being able to write there. Perhaps try moving the site you're building out of the trash?

**Comment by heyallan** [comment]
Weird, my working dir is normal:

```
$ pwd
/Volumes/GUEST/projects/tutorials/enfield
```

Either way…

- I deleted everything and started all over
- Updated node (just in case)
- Reinstalled enfield
- Rerun enfield
- Got new error: `Error: spawn pygmentize ENOENT`
- Opened `_config.yml`, set it to `pygments: false`
- Rerun enfield again
- It works!

Not sure why though, lack of documentation made me feel unsure.
I love the idea of enfield, I'll play with it a bit more.

**Thank you very much anyway!**
